spring:
  application:
    name: kafka-to-elastic
  profiles:
    active: kafka_to_elastic
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-to-elastic,config-client
      username: admin
      password: '{cipher}fa2f9ece28c133474cc76d1810e35a537cd91de792a7d6d0a07ee1d99bb21e7a'