twitter-to-kafka-service:
  twitter-keywords:
    - ksqldb
    - Kafka
    - kafka-connect
    - kafka stream
    - Java
    - Elasticsearch
  welcome-message: Hello world
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

